### ISSUE TITLE
Unable to get plantuml-viewer to work reliably

### ISSUE THREAD

**Issue by guinnsquirrel** [markushedvall/plantuml-viewer#11]
Hello,

I have the following setup:
* Atom: v1.2.0
* plantuml-viewer: v0.7.0
* graphviz: v2.36.0

ON Apple OSX 10.10.xx

IO cannot reliably render plantuml content. I can toggle the view once, per session, then never again. Really not too sure what I am doing wrong. I am also using Apple version of Java.

Can you assist?

**Comment by yalla** [comment]
I'm having the same issue on Windows.

Details:
* Windows 7 Enterprise SP1
* Atom 1.4.3 (official build)
* plantuml-viewer 0.7.0
* Oracle JRE SE 1.7.0_67

As @guinnsquirrel described, I can display it once. Live-updates while typing don't work. To generate an updated view I have to restart Atom completely.
This happens no matter if Graphviz is installed or not.

Any idea?

**Comment by toeryn** [comment]
Exactly the same issue in Linux.

Details:
- Linux Mint 17.3 Rosa
- Atom 1.5.4
- plantuml-viewer: v0.7.0
- graphviz version v2.36.0 (20140111.2315)

**Comment by mabstorm** [comment]
I think I fixed this issue here: https://github.com/markushedvall/plantuml-viewer/pull/16

**Comment by Muzamri** [comment]
Thanks @mabstorm, live updates + window toggling works for me now.

**Comment by zeigerpuppy** [comment]
Not working for me either, I briefly see the diagram shown in the preview when it is first opened, then the preview remains blank.

OS X 10.9.5
Atom 1.7.4
graphviz version 2.38.0 (20140413.2041) - via macports

**Comment by yieme** [comment]
Same apparent issue. Preview opens, briefly flashes a correctly rendered image then goes blank and stays blank.

- OS X `10.10.5`
- Atom `1.7.4`
- dot - graphviz version `2.38.0` (20140413.2041)
- plantuml-viewer `0.7.0`
- Atom terminal shell shows GRAPHVIZ_DOT is correctly pointing to `/usr/local/bin/dot`

Same issue with plantuml-viewer `0.5.0`, `0.6.0` & `0.6.1`.

Getting into the code with #16 might fix the issue and it probably should be a pull request; however, I found the following worked without getting into the code.

Downgrade to plantuml-viewer `0.4.1`. Exit atom, then:

```sh
apm rm plantuml-viewer
apm i plantuml-viewer@0.4.1
```

**Comment by coolboy0961** [comment]
I fixed this issue by upgrading java from 1.7.0_55 to 1.8.0_101-b13.

**Comment by yieme** [comment]
Thanks @coolboy0961, I gave it a try. Unfortunately, nothing renders with `plantuml-viewer@0.7.0`. Just a blank display without even the correctly rendered image even briefly displaying. Reverting to `0.4.1` and all is well.

**Comment by wkmcyz** [comment]
My plantuml-viewer gets back to work after i disable my markdown-viewer package,guess something crashes between them.

**Comment by wkmcyz** [comment]
0.4.1 is able to work.

**Comment by MaciekLeks** [comment]
Still the same effect for the given OS and Atom elements:

- OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)                                          │
- plantuml-viewer@0.7.2
